import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  appShell: {
    minHeight: '100dvh',
    background: 'var(--color-bg)',
    display: 'flex',
    flexDirection: 'column',
  },
  contentWrapper: {
    flex: 1,
    overflowY: 'auto',
    paddingBottom: '100px',
  },
  header: {
    background: 'linear-gradient(160deg, #e8f4fd 0%, #d4eaf7 50%, #c8e8e0 100%)',
    padding: '56px 24px 24px',
    borderRadius: '0 0 28px 28px',
  },
  headerTitle: {
    fontSize: '22px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 4px',
  },
  headerSubtitle: {
    fontSize: '13px',
    color: 'var(--color-text-muted)',
    margin: 0,
  },
  searchBar: {
    marginTop: '16px',
    background: 'rgba(255,255,255,0.75)',
    borderRadius: '14px',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    border: '1px solid var(--color-border)',
  },
  searchIcon: {
    // SVG styles are handled inline in the component
  },
  searchText: {
    fontSize: '14px',
    color: 'var(--color-text-light)',
  },
  pageContent: {
    padding: '24px',
  },
  categoryFilter: {
    display: 'flex',
    gap: '8px',
    overflowX: 'auto',
    marginBottom: '20px',
    paddingBottom: '4px',
  },
  h3: {
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 12px',
  },
  quickPracticesContainer: {
    display: 'flex',
    gap: '10px',
    marginBottom: '24px',
  },
  practiceButton: {
    flex: 1,
    background: 'var(--color-bg-card)',
    borderRadius: '16px',
    padding: '14px 10px',
    border: '1px solid var(--color-border)',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
    textAlign: 'center',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
  },
  practiceIcon: {
    fontSize: '22px',
  },
  practiceLabel: {
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--color-text)',
  },
  practiceDuration: {
    fontSize: '10px',
    background: 'var(--color-bg)',
    color: 'var(--color-secondary-dark)',
    borderRadius: '6px',
    padding: '2px 7px',
    fontWeight: 600,
  },
  practiceDesc: {
    fontSize: '10px',
    color: 'var(--color-text-muted)',
    lineHeight: 1.3,
  },
  articleCard: {
    borderRadius: '18px',
    padding: '18px',
    marginBottom: '12px',
    cursor: 'pointer',
    display: 'flex',
    gap: '14px',
    alignItems: 'flex-start',
  },
  articleIconContainer: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    background: 'rgba(255,255,255,0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '24px',
    flexShrink: 0,
  },
  articleContent: {
    flex: 1,
  },
  articleMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '4px',
  },
  articleCategory: {
    fontSize: '10px',
    fontWeight: 700,
    color: 'var(--color-text-muted)',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  articleReadTime: {
    fontSize: '11px',
    color: 'var(--color-text-light)',
  },
  articleTitle: {
    margin: '0 0 5px',
    fontSize: '15px',
    fontWeight: 600,
    color: 'var(--color-text)',
    lineHeight: 1.3,
  },
  articleDesc: {
    margin: 0,
    fontSize: '13px',
    color: 'var(--color-text-muted)',
    lineHeight: 1.5,
  },
  skeletonCard: {
    backgroundColor: '#f0f0f0',
    borderRadius: '18px',
    padding: '18px',
    marginBottom: '12px',
    display: 'flex',
    gap: '14px',
    alignItems: 'flex-start',
  },
  skeletonIcon: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    backgroundColor: '#e0e0e0',
  },
  skeletonTextContainer: {
    flex: 1,
  },
  skeletonText: {
    backgroundColor: '#e0e0e0',
    height: '1em',
    borderRadius: '4px',
    marginBottom: '8px',
  },
};
