import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  appShell: {
    minHeight: '100dvh',
    background: 'var(--color-bg)',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  header: {
    background: 'linear-gradient(160deg, #e8f4fd 0%, #d4eaf7 50%, #c8e8e0 100%)',
    padding: '56px 24px 24px',
    borderRadius: '0 0 28px 28px',
  },
  headerContent: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: '22px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 4px',
  },
  headerSubtitle: {
    fontSize: '13px',
    color: 'var(--color-text-muted)',
    margin: 0,
  },
  streakPill: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(255,255,255,0.6)',
    borderRadius: '999px',
    padding: '6px 10px',
    border: '1px solid rgba(255,255,255,0.7)',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--color-text)',
  },
  newEntryButton: {
    background: 'linear-gradient(135deg, var(--color-primary-dark), var(--color-primary))',
    border: 'none',
    borderRadius: '12px',
    padding: '8px 12px',
    color: 'white',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    boxShadow: '0 3px 10px rgba(58,125,191,0.24)',
  },
  floatingStreak: {
    position: 'absolute',
    top: '112px',
    right: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(255,255,255,0.95)',
    borderRadius: '999px',
    padding: '6px 10px',
    border: '1px solid rgba(255,255,255,0.7)',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--color-text)',
    zIndex: 30,
    boxShadow: '0 6px 14px rgba(15, 23, 42, 0.12)',
    backdropFilter: 'blur(6px)',
  },
};
