import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  h3: {
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 12px',
  },
  composeContainer: {
    background: 'var(--color-bg-card)',
    borderRadius: '20px',
    padding: '20px',
    marginBottom: '20px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
    border: '1px solid var(--color-primary-light)',
  },
  moodSelectorContainer: {
    display: 'flex',
    gap: '8px',
    marginBottom: '16px',
  },
  moodButton: {
    flex: 1,
    padding: '10px 0',
    borderRadius: '12px',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    transition: 'all 0.2s',
  },
  moodEmoji: {
    fontSize: '20px',
  },
  moodLabel: {
    fontSize: '9px',
    color: 'var(--color-text-muted)',
    fontWeight: 500,
  },
  textarea: {
    width: '100%',
    padding: '14px',
    borderRadius: '12px',
    border: '1.5px solid var(--color-border)',
    background: 'var(--color-bg)',
    fontSize: '15px',
    color: 'var(--color-text)',
    resize: 'none',
    outline: 'none',
    lineHeight: 1.6,
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  composeActions: {
    display: 'flex',
    gap: '10px',
    marginTop: '12px',
  },
  cancelButton: {
    flex: 1,
    padding: '13px',
    borderRadius: '12px',
    border: '1.5px solid var(--color-border)',
    background: 'transparent',
    fontSize: '14px',
    fontWeight: 600,
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
  },
  saveButton: {
    flex: 2,
    padding: '13px',
    borderRadius: '12px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 600,
  },
  entryCard: {
    background: 'var(--color-bg-card)',
    borderRadius: '16px',
    padding: '16px',
    marginBottom: '12px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.04)',
    cursor: 'pointer',
    border: '1px solid var(--color-border)',
  },
  entryHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '8px',
  },
  entryDate: {
    margin: 0,
    fontSize: '10px',
    color: 'var(--color-text-light)',
    letterSpacing: '0.04em',
  },
  entryTitle: {
    margin: '4px 0 0',
    fontSize: '15px',
    fontWeight: 600,
    color: 'var(--color-text)',
  },
  entryMood: {
    fontSize: '24px',
    flexShrink: 0,
  },
  entryPreview: {
    margin: '0 0 10px',
    fontSize: '13px',
    color: 'var(--color-text-muted)',
    lineHeight: 1.6,
  },
  tagsContainer: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  },
  tag: {
    fontSize: '11px',
    background: 'var(--color-bg)',
    color: 'var(--color-primary-dark)',
    borderRadius: '8px',
    padding: '3px 8px',
    fontWeight: 500,
    border: '1px solid var(--color-primary-light)',
  },
  skeletonCard: {
    backgroundColor: '#f0f0f0',
    borderRadius: '16px',
    padding: '16px',
    marginBottom: '12px',
  },
  skeletonText: {
    backgroundColor: '#e0e0e0',
    height: '1em',
    borderRadius: '4px',
    marginBottom: '8px',
  },
};
