import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  appShell: {
    minHeight: "100dvh",
    background: "var(--color-bg)",
    display: "flex",
    flexDirection: "column",
  },
  pageContent: {
    flex: 1,
    overflowY: "auto",
    paddingBottom: "100px",
  },
  header: {
    background: "linear-gradient(160deg, #e8f4fd 0%, #d4eaf7 50%, #c8e8e0 100%)",
    padding: "56px 24px 24px",
    textAlign: "center",
    borderRadius: "0 0 28px 28px",
  },
  headerSettingsRow: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: "16px",
  },
  headerSettingsButton: {
    background: "rgba(255,255,255,0.6)",
    border: "none",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  headerAvatarRow: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "14px",
  },
  headerAvatarWrap: {
    position: "relative",
    display: "inline-block",
  },
  headerAvatarCircle: {
    width: "76px",
    height: "76px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, var(--color-primary), var(--color-secondary))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "30px",
    fontWeight: 700,
    color: "white",
    boxShadow: "0 6px 20px rgba(91,155,213,0.35)",
    border: "3px solid white",
  },
  headerAvatarBadge: {
    position: "absolute",
    bottom: "2px",
    right: "2px",
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    background: "var(--color-secondary)",
    border: "2px solid white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  headerName: {
    fontSize: "20px",
    fontWeight: 700,
    color: "var(--color-text)",
    margin: "0 0 3px",
  },
  headerEmail: {
    fontSize: "13px",
    color: "var(--color-text-muted)",
    margin: "0 0 8px",
  },
  headerMemberBadge: {
    display: "inline-block",
    background: "rgba(91,155,213,0.15)",
    color: "var(--color-primary-dark)",
    borderRadius: "20px",
    padding: "3px 12px",
    fontSize: "11px",
    fontWeight: 600,
  },
  tabs: {
    display: "flex",
    margin: "20px 20px 0",
    background: "#f1f5f9",
    borderRadius: "14px",
    padding: "4px",
    gap: "2px",
  },
  tabButton: {
    flex: 1,
    padding: "9px 0",
    border: "none",
    borderRadius: "11px",
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  tabButtonActive: {
    fontWeight: 700,
    background: "white",
    color: "var(--color-primary-dark)",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },
  tabButtonInactive: {
    fontWeight: 500,
    background: "transparent",
    color: "var(--color-text-muted)",
    boxShadow: "none",
  },
  sectionWrap: {
    padding: "20px 20px 0",
  },
  sectionTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "var(--color-text-muted)",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    margin: "0 0 12px",
  },
  statGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    marginBottom: "28px",
  },
  statCard: {
    borderRadius: "18px",
    padding: "16px",
    position: "relative",
    overflow: "hidden",
  },
  statValue: {
    fontSize: "28px",
    fontWeight: 800,
    lineHeight: 1,
  },
  statUnit: {
    fontSize: "11px",
    opacity: 0.65,
    marginTop: "2px",
  },
  statLabel: {
    fontSize: "11px",
    fontWeight: 600,
    color: "var(--color-text-muted)",
    marginTop: "5px",
  },
  achievementsList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  achievementCard: {
    borderRadius: "16px",
    padding: "14px 16px",
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  achievementIconBox: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
    flexShrink: 0,
  },
  achievementRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "4px",
  },
  achievementLabel: {
    fontSize: "13px",
    fontWeight: 700,
    color: "var(--color-text)",
  },
  achievementUnlockedBadge: {
    fontSize: "10px",
    fontWeight: 700,
    borderRadius: "20px",
    padding: "2px 8px",
  },
  achievementProgressText: {
    fontSize: "11px",
    color: "var(--color-text-muted)",
    fontWeight: 600,
  },
  achievementDesc: {
    fontSize: "11px",
    color: "var(--color-text-muted)",
    margin: "0 0 8px",
    lineHeight: 1.4,
  },
  progressTrack: {
    height: "5px",
    borderRadius: "99px",
    background: "#e5e7eb",
    overflow: "hidden",
  },
  chartCard: {
    background: "var(--color-bg-card)",
    borderRadius: "20px",
    padding: "18px",
    marginBottom: "14px",
    boxShadow: "0 2px 12px rgba(0,0,0,0.04)",
    border: "1px solid var(--color-border)",
  },
  chartHeader: {
    marginBottom: "4px",
  },
  chartTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "var(--color-text)",
    margin: 0,
  },
  chartSubtitle: {
    fontSize: "11px",
    color: "var(--color-text-muted)",
    margin: "3px 0 14px",
  },
  legendRow: {
    display: "flex",
    gap: "16px",
    marginBottom: "12px",
    flexWrap: "wrap",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
  legendSwatch: {
    width: "10px",
    height: "10px",
    borderRadius: "3px",
    flexShrink: 0,
  },
  legendLabel: {
    fontSize: "11px",
    color: "var(--color-text-muted)",
  },
  chartCanvas: {
    position: "relative",
    width: "100%",
  },
  chartFooter: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "10px",
    fontSize: "12px",
    color: "var(--color-text-muted)",
  },
  chartLegendColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "16px",
  },
  chartLegendRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  chartLegendLabel: {
    fontSize: "12px",
    color: "var(--color-text)",
    flex: 1,
  },
  chartLegendValue: {
    fontSize: "11px",
    fontWeight: 700,
    color: "var(--color-text-muted)",
  },
  chartLegendPct: {
    fontSize: "10px",
    color: "var(--color-text-muted)",
    minWidth: "30px",
    textAlign: "right",
  },
  resourcesCrisisCard: {
    background: "linear-gradient(135deg, #fef2f2, #fff1f2)",
    border: "2px solid #fecaca",
    borderRadius: "20px",
    padding: "18px",
    marginBottom: "18px",
  },
  resourcesCrisisHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
  },
  resourcesCrisisTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#991b1b",
  },
  resourcesCrisisSubtitle: {
    fontSize: "11px",
    color: "#dc2626",
  },
  resourcesCrisisActions: {
    display: "flex",
    gap: "8px",
  },
  resourcesCrisisButton: {
    background: "#dc2626",
    color: "white",
    borderRadius: "12px",
    padding: "10px",
    textAlign: "center",
    fontSize: "13px",
    fontWeight: 700,
  },
  resourcesSection: {
    marginBottom: "20px",
  },
  resourcesSectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "10px",
  },
  resourcesSectionName: {
    fontSize: "14px",
    fontWeight: 700,
    color: "var(--color-text)",
    margin: 0,
  },
  resourcesList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  resourcesCard: {
    background: "var(--color-bg-card)",
    border: "1.5px solid var(--color-border)",
    borderRadius: "14px",
    padding: "14px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
  },
  resourcesCardContent: {
    flex: 1,
    minWidth: 0,
  },
  resourcesCardName: {
    fontSize: "13px",
    fontWeight: 600,
    color: "var(--color-text)",
    marginBottom: "2px",
  },
  resourcesCardDesc: {
    fontSize: "11px",
    color: "var(--color-text-muted)",
    marginBottom: "5px",
  },
  resourcesCardTag: {
    display: "inline-block",
    borderRadius: "8px",
    padding: "2px 8px",
    fontSize: "10px",
    fontWeight: 600,
  },
  resourcesCardIconBox: {
    width: "32px",
    height: "32px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  selfExclusionCard: {
    background: "var(--color-bg-card)",
    border: "1.5px solid var(--color-secondary-light)",
    borderRadius: "18px",
    padding: "16px",
    marginBottom: "24px",
  },
  selfExclusionTitle: {
    fontSize: "13px",
    fontWeight: 700,
    color: "var(--color-text)",
    marginBottom: "4px",
  },
  selfExclusionDesc: {
    fontSize: "11px",
    color: "var(--color-text-muted)",
    marginBottom: "12px",
    lineHeight: 1.5,
  },
  selfExclusionLink: {
    background: "var(--color-bg)",
    border: "1px solid var(--color-border)",
    borderRadius: "10px",
    padding: "10px 14px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "6px",
    fontSize: "12px",
    fontWeight: 600,
    color: "var(--color-text)",
  },
  spacer: {
    height: "24px",
  },
};
