export const Colors = {
  primary: '#5b9bd5',
  primaryDark: '#3a7dbf',
  primaryLight: '#bfdbfe',
  secondary: '#7ab89a',
  secondaryDark: '#4f9a74',
  secondaryLight: '#bbf7d0',
  accent: '#e8b86d',
  bg: '#f0f4f8',
  bgCard: '#ffffff',
  text: '#2d3748',
  textMuted: '#718096',
  textLight: '#a0aec0',
  border: '#e2e8f0',
  warningBg: '#fffbeb',
  warningBorder: '#fde68a',
  warningCritical: '#fca5a5',
  white: '#ffffff',
  black: '#111111',
} as const;
