import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  appShell: {
    minHeight: '100dvh',
    background: 'var(--color-bg)',
    display: 'flex',
    flexDirection: 'column',
  },
  contentWrapper: {
    flex: 1,
    overflowY: 'auto',
    paddingBottom: '100px',
  },
  pageContent: {
    padding: '24px',
  },
  h3: {
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 12px',
  },
  header: {
    background: 'linear-gradient(160deg, #e8f4fd 0%, #d4eaf7 60%, #c8e8e0 100%)',
    padding: '56px 24px 28px',
    borderRadius: '0 0 28px 28px',
  },
  headerContent: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontSize: '26px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 4px',
    letterSpacing: '-0.02em',
  },
  headerSubtitle: {
    fontSize: '14px',
    color: 'var(--color-text-muted)',
    margin: 0,
  },
  headerActions: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
  },
  notificationButton: {
    background: 'rgba(255,255,255,0.6)',
    border: 'none',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  avatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, var(--color-primary), var(--color-secondary))',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 700,
    fontSize: '16px',
  },
  realityCheckCard: {
    marginTop: '20px',
    background: 'var(--color-warning-bg)',
    border: '1px solid var(--color-warning-border)',
    borderRadius: '16px',
    padding: '16px 18px',
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
  },
  realityCheckIconContainer: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    background: '#fef3c7',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  realityCheckTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#92400e',
    margin: '0 0 3px',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  realityCheckText: {
    fontSize: '14px',
    color: '#78350f',
    margin: 0,
    lineHeight: 1.5,
  },
  weeklyStreakContainer: {
    background: 'var(--color-bg-card)',
    borderRadius: '20px',
    padding: '20px',
    marginBottom: '16px',
    boxShadow: '0 2px 16px rgba(0,0,0,0.05)',
  },
  weeklyStreakHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  weeklyStreakTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: 'var(--color-text)',
    margin: '0 0 2px',
  },
  weeklyStreakSubtitle: {
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    margin: 0,
  },
  streakCounter: {
    background: 'linear-gradient(135deg, #fef9ec, #fef3c7)',
    borderRadius: '12px',
    padding: '6px 12px',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  streakCount: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#92400e',
  },
  weekDaysContainer: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  dayContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
  },
  dayCircle: {
    width: '38px',
    height: '38px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s',
  },
  dayLabel: {
    fontSize: '11px',
  },
  ctaButton: {
    width: '100%',
    padding: '18px',
    borderRadius: '16px',
    background: 'linear-gradient(135deg, var(--color-secondary-dark), var(--color-secondary))',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 8px 24px rgba(79,154,116,0.3)',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s',
  },
  ctaButtonCompleted: {
    width: '100%',
    padding: '18px',
    borderRadius: '16px',
    background: 'linear-gradient(135deg, #f0fdf4, #dcfce7)',
    border: '1.5px solid #86efac',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    boxSizing: 'border-box',
  },
  ctaButtonCompletedText: {
    margin: 0,
    fontSize: '15px',
    fontWeight: 600,
    color: '#166534',
  },
  ctaButtonCompletedSubtext: {
    margin: 0,
    fontSize: '12px',
    color: '#4ade80',
  },
  reflectionPromptContainer: {
    background: 'linear-gradient(135deg, #eef6ff, #e8f4fd)',
    border: '1px solid var(--color-primary-light)',
    borderRadius: '20px',
    padding: '20px',
    marginBottom: '16px',
  },
  reflectionPromptHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '10px',
  },
  reflectionPromptTitle: {
    margin: 0,
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--color-primary-dark)',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  reflectionPromptText: {
    fontSize: '16px',
    color: 'var(--color-text)',
    margin: '0 0 14px',
    lineHeight: 1.6,
    fontWeight: 500,
  },
  reflectionPromptButton: {
    background: 'var(--color-primary)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    padding: '10px 18px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  quickActionsContainer: {
    display: 'flex',
    gap: '10px',
    marginBottom: '16px',
  },
  quickActionLink: {
    textDecoration: 'none',
    flex: 1,
  },
  quickActionCard: {
    background: 'var(--color-bg-card)',
    borderRadius: '16px',
    padding: '16px 10px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.04)',
    cursor: 'pointer',
    transition: 'transform 0.15s',
    border: '1px solid var(--color-border)',
  },
  quickActionIcon: {
    fontSize: '22px',
  },
  quickActionLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--color-text-muted)',
    textAlign: 'center',
    lineHeight: 1.3,
  },
  recentInsightsContainer: {
    // No specific container style needed
  },
  insightCard: {
    borderRadius: '14px',
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    marginBottom: '10px',
  },
  insightIcon: {
    fontSize: '24px',
  },
  insightTitle: {
    margin: '0 0 2px',
    fontSize: '14px',
    fontWeight: 600,
    color: 'var(--color-text)',
  },
  insightDesc: {
    margin: 0,
    fontSize: '12px',
    color: 'var(--color-text-muted)',
  },
  skeletonCard: {
    backgroundColor: '#f0f0f0',
    borderRadius: '20px',
    padding: '20px',
    marginBottom: '16px',
  },
  skeletonHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  skeletonText: {
    backgroundColor: '#e0e0e0',
    height: '1em',
    borderRadius: '4px',
  },
  skeletonCircle: {
    backgroundColor: '#e0e0e0',
    borderRadius: '50%',
  },
};
