import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  appShell: {
    minHeight: "100dvh",
    background: "var(--color-bg)",
    display: "flex",
    flexDirection: "column",
  },
  pageContent: {
    flex: 1,
    overflowY: "auto",
    paddingBottom: "100px",
  },
  header: {
    background: "linear-gradient(160deg, #e8f4fd 0%, #d4eaf7 60%, #c8e8e0 100%)",
    padding: "56px 24px 28px",
    borderRadius: "0 0 28px 28px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  headerBackButton: {
    background: "rgba(255,255,255,0.6)",
    border: "none",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: "22px",
    fontWeight: 700,
    color: "var(--color-text)",
    margin: 0,
    letterSpacing: "-0.02em",
  },
  headerSubtitle: {
    fontSize: "13px",
    color: "var(--color-text-muted)",
    margin: 0,
  },
  contentWrap: {
    padding: "24px",
  },
  sectionHeader: {
    fontSize: "12px",
    fontWeight: 700,
    color: "var(--color-text-muted)",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    margin: "0 0 10px",
    paddingLeft: "4px",
  },
  card: {
    background: "var(--color-bg-card)",
    borderRadius: "16px",
    overflow: "hidden",
    marginBottom: "20px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.04)",
  },
  rowButton: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    width: "100%",
    padding: "14px 16px",
    background: "none",
    border: "none",
    textAlign: "left",
    borderBottom: "1px solid var(--color-border)",
    transition: "background 0.15s",
  },
  rowIcon: {
    width: "38px",
    height: "38px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "18px",
    flexShrink: 0,
  },
  rowContent: {
    flex: 1,
  },
  rowLabel: {
    margin: 0,
    fontSize: "15px",
    fontWeight: 500,
  },
  rowDesc: {
    margin: 0,
    fontSize: "12px",
    color: "var(--color-text-muted)",
    marginTop: "1px",
  },
  toggleButton: {
    width: "48px",
    height: "28px",
    borderRadius: "14px",
    border: "none",
    cursor: "pointer",
    position: "relative",
    transition: "background 0.25s ease",
    flexShrink: 0,
  },
  toggleThumb: {
    position: "absolute",
    top: "3px",
    width: "22px",
    height: "22px",
    borderRadius: "50%",
    background: "white",
    boxShadow: "0 2px 6px rgba(0,0,0,0.15)",
    transition: "left 0.25s ease",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "14px 16px",
  },
  toggleRowContent: {
    flex: 1,
  },
  toggleLabel: {
    margin: 0,
    fontSize: "15px",
    fontWeight: 500,
    color: "var(--color-text)",
  },
  toggleDesc: {
    margin: 0,
    fontSize: "12px",
    color: "var(--color-text-muted)",
    marginTop: "2px",
  },
  dangerText: {
    color: "#dc2626",
  },
  dangerIconBg: {
    background: "#fee2e2",
  },
  normalIconBg: {
    background: "var(--color-bg)",
  },
  versionText: {
    textAlign: "center",
    fontSize: "12px",
    color: "var(--color-text-light)",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "flex-end",
    zIndex: 100,
  },
  modalSheet: {
    background: "var(--color-bg-card)",
    borderRadius: "24px 24px 0 0",
    padding: "28px 24px 40px",
    width: "100%",
    boxSizing: "border-box",
  },
  modalHeader: {
    textAlign: "center",
    marginBottom: "20px",
  },
  modalIcon: {
    fontSize: "44px",
    marginBottom: "10px",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "var(--color-text)",
    margin: "0 0 8px",
  },
  modalText: {
    fontSize: "14px",
    color: "var(--color-text-muted)",
    margin: 0,
    lineHeight: "1.5",
  },
  modalPrimaryButton: {
    width: "100%",
    padding: "14px",
    borderRadius: "14px",
    background: "#dc2626",
    color: "white",
    fontSize: "15px",
    fontWeight: 700,
    border: "none",
    cursor: "pointer",
    marginBottom: "10px",
  },
  modalSecondaryButton: {
    width: "100%",
    padding: "14px",
    borderRadius: "14px",
    background: "var(--color-bg)",
    color: "var(--color-text-muted)",
    fontSize: "15px",
    fontWeight: 600,
    border: "none",
    cursor: "pointer",
  },
};
